name: code_buffer
version: 1.0.1
description: An advanced StringBuffer geared toward generating code, and source maps.
author: Tobe O <thosakwe@gmail.com>
homepage: https://github.com/thosakwe/code_buffer
environment:
  sdk: ">=1.8.0 <3.0.0"
dependencies:
  charcode: ^1.0.0
  source_span: ^1.0.0
dev_dependencies:
  test: ^0.12.0